version: '3.8'

services:
  api:
    image: xydatalabs-orderprocessingsystem-api
    build:
      context: .
      dockerfile: XYDataLabs.OrderProcessingSystem.API/Dockerfile
    ports:
      - "5000:8080"  # HTTP
      - "5001:8081"  # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    networks:
      - xynetwork
    healthcheck:
      test: curl --fail http://localhost:8080/swagger || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ui:
    image: xydatalabs-orderprocessingsystem-ui
    build:
      context: .
      dockerfile: XYDataLabs.OrderProcessingSystem.UI/Dockerfile
    ports:
      - "5002:8080"  # HTTP
      - "5003:8081"  # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - API_BASE_URL=http://api:8080
    depends_on:
      api:
        condition: service_healthy
    networks:
      - xynetwork
    healthcheck:
      test: curl --fail http://localhost:8080/Home/Error || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  xynetwork:
    driver: bridge
