# UAT Environment - Complete Configuration
# Usage: docker-compose -f docker-compose.uat.yml --profile http up
# Purpose: UAT testing configuration with production-like settings

services:
  api-uat-http:
    image: xydatalabs-orderprocessingsystem-api-http:uat
    build:
      context: .
      dockerfile: XYDataLabs.OrderProcessingSystem.API/Dockerfile
      target: final
    ports:
      - "5030:5030"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:5030
      - ASPNETCORE_HTTP_PORTS=5030
      - USE_HTTPS=false
    volumes:
      - ./logs:/logs
      - ./Resources/Certificates/aspnetapp.pfx:/https/aspnetapp.pfx:ro
      - ./Resources/Configuration/sharedsettings.uat.json:/app/Resources/Configuration/sharedsettings.uat.json:ro
    networks:
      - xy-uat-network
      - xy-database-network
    profiles: ["http", "all", "api"]
    healthcheck:
      test: curl --fail http://localhost:5030/swagger --insecure || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s

  api-uat-https:
    image: xydatalabs-orderprocessingsystem-api-https:uat
    build:
      context: .
      dockerfile: XYDataLabs.OrderProcessingSystem.API/Dockerfile
      target: final
    ports:
      - "5031:5031"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:5031
      - ASPNETCORE_HTTPS_PORTS=5031
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ss100
    volumes:
      - ./logs:/logs
      - ./Resources/Certificates/aspnetapp.pfx:/https/aspnetapp.pfx:ro
      - ./Resources/Configuration/sharedsettings.uat.json:/app/Resources/Configuration/sharedsettings.uat.json:ro
    networks:
      - xy-uat-network
      - xy-database-network
    profiles: ["https", "all", "api-https"]
    healthcheck:
      test: curl --fail https://localhost:5031/swagger --insecure || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s

  ui-uat-http:
    image: xydatalabs-orderprocessingsystem-ui-http:uat
    build:
      context: .
      dockerfile: XYDataLabs.OrderProcessingSystem.UI/Dockerfile
      target: final
    ports:
      - "5032:5032"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:5032
      - ASPNETCORE_HTTP_PORTS=5032
      - ApiSettings__BaseUrl=http://localhost:5030
      - USE_HTTPS=false
    volumes:
      - ./Resources/Configuration/sharedsettings.uat.json:/app/Resources/Configuration/sharedsettings.uat.json:ro
      - ./logs:/logs
    networks:
      - xy-uat-network
    profiles: ["http", "all", "ui"]
    depends_on:
      api-uat-http:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:5032 --insecure || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s

  ui-uat-https:
    image: xydatalabs-orderprocessingsystem-ui-https:uat
    build:
      context: .
      dockerfile: XYDataLabs.OrderProcessingSystem.UI/Dockerfile
      target: final
    ports:
      - "5033:5033"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:5033
      - ASPNETCORE_HTTPS_PORTS=5033
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ss100
      - ApiSettings__BaseUrl=https://localhost:5031
    volumes:
      - ./Resources/Certificates/aspnetapp.pfx:/https/aspnetapp.pfx:ro
      - ./Resources/Configuration/sharedsettings.uat.json:/app/Resources/Configuration/sharedsettings.uat.json:ro
      - ./logs:/logs
    networks:
      - xy-uat-network
    profiles: ["https", "all", "ui-https"]
    depends_on:
      api-uat-https:
        condition: service_healthy
    healthcheck:
      test: curl --fail https://localhost:5033 --insecure || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s

# UAT networking
networks:
  xy-uat-network:
    external: true
  xy-database-network:
    external: true
