#Requires -Version 7.0
<#
.SYNOPSIS
    Bootstrap local development environment. Run once after a fresh clone.

.DESCRIPTION
    Performs all first-time setup needed to develop and run this project locally:
      1. Creates Resources/Docker/.env.local — prompts for passwords on first run,
         reads them from the existing file on subsequent runs.
      2. Sets dotnet user-secrets for VS F5 and dotnet run (API + UI projects)
      3. Trusts the HTTPS development certificate

    .env.local is the single source of truth for local passwords. All steps derive
    passwords from it — no hardcoded defaults, no parameters to pass.

    This script is idempotent: re-running it reads from the existing .env.local and
    re-applies user-secrets and cert without prompting again.
    Use -Force to re-prompt for passwords and overwrite everything.

.PARAMETER Force
    Re-prompt for passwords, recreate .env.local, and overwrite dotnet user-secrets
    and the dev certificate even if they already exist.

.EXAMPLE
    # First-time setup — prompts for SQL and cert passwords
    .\scripts\setup-local.ps1

.EXAMPLE
    # Re-run and overwrite everything (e.g. after a password change)
    .\scripts\setup-local.ps1 -Force

.NOTES
    After running this script:
      - F5 in Visual Studio 2022 is ready immediately (no prompts).
      - Docker: .\Resources\Docker\start-docker.ps1 -Environment dev -Profile http
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ─── Paths ───────────────────────────────────────────────────────────────────
$root       = Split-Path $PSScriptRoot -Parent
$envExample = Join-Path $root 'Resources\Docker\.env.local.example'
$envLocal   = Join-Path $root 'Resources\Docker\.env.local'
$certFile   = Join-Path $root 'Resources\Certificates\aspnetapp.pfx'
$apiCsproj  = Join-Path $root 'XYDataLabs.OrderProcessingSystem.API\XYDataLabs.OrderProcessingSystem.API.csproj'
$uiCsproj   = Join-Path $root 'XYDataLabs.OrderProcessingSystem.UI\XYDataLabs.OrderProcessingSystem.UI.csproj'

# ─── Helpers ──────────────────────────────────────────────────────────────────
function Write-Step([string] $msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Done([string] $msg) { Write-Host "    [ok]  $msg" -ForegroundColor Green }
function Write-Skip([string] $msg) { Write-Host "    [--]  $msg (already done — skip)" -ForegroundColor DarkGray }

function Read-Password([string] $prompt) {
    $ss = Read-Host -Prompt $prompt -AsSecureString
    [System.Net.NetworkCredential]::new('', $ss).Password
}

function Read-EnvLocal([string] $path) {
    $vars = @{}
    Get-Content $path | Where-Object { $_ -match '^[A-Z]' } | ForEach-Object {
        $parts = $_ -split '=', 2
        if ($parts.Count -eq 2) { $vars[$parts[0].Trim()] = $parts[1].Trim() }
    }
    $vars
}

# ─── 1. Docker .env.local ─────────────────────────────────────────────────────
Write-Step 'Docker secrets — Resources/Docker/.env.local'

if ((Test-Path $envLocal) -and -not $Force) {
    Write-Skip '.env.local already exists — reading passwords from it'
    $envVars      = Read-EnvLocal $envLocal
    $certPassword = $envVars['LOCAL_CERT_PASSWORD']
    $sqlPassword  = $envVars['LOCAL_SQL_PASSWORD']
}
else {
    if (-not (Test-Path $envExample)) {
        Write-Error "Expected template not found: $envExample"
    }

    Write-Host '  Choose passwords for your local sandbox — you are setting these for the first time.' -ForegroundColor Yellow
    Write-Host '  They will be saved to .env.local and used for every subsequent run.' -ForegroundColor Yellow
    Write-Host '  SQL Server requires: 8+ chars, uppercase, lowercase, digit, special char (e.g. MyLocal1!)' -ForegroundColor DarkGray
    Write-Host ''
    $sqlPassword  = Read-Password '  Choose SQL Server password (LOCAL_SQL_PASSWORD) '
    $certPassword = Read-Password '  Choose HTTPS cert password (LOCAL_CERT_PASSWORD) '

    $content = @"
# Local Docker secrets — auto-generated by setup-local.ps1
# Gitignored. Re-run setup-local.ps1 -Force to change passwords.
LOCAL_SQL_PASSWORD=$sqlPassword
LOCAL_CERT_PASSWORD=$certPassword
LOCAL_OPENPAY_MERCHANT_ID=local-sandbox-only
LOCAL_OPENPAY_PRIVATE_KEY=local-sandbox-only
LOCAL_OPENPAY_DEVICE_SESSION_ID=default-device-session
"@
    Set-Content -Path $envLocal -Value $content -Encoding UTF8
    Write-Done 'Created .env.local'
}

# ─── 2. dotnet user-secrets (API) ─────────────────────────────────────────────
Write-Step 'dotnet user-secrets — API project'

$apiSecrets = [ordered]@{
    'ApiSettings:API:https:CertPassword' = $certPassword
    'OpenPay:MerchantId'                 = 'local-sandbox-only'
    'OpenPay:PrivateKey'                 = 'local-sandbox-only'
    'OpenPay:DeviceSessionId'            = 'default-device-session'
}

foreach ($kv in $apiSecrets.GetEnumerator()) {
    if ($PSCmdlet.ShouldProcess("API user-secrets: $($kv.Key)")) {
        dotnet user-secrets set $kv.Key $kv.Value --project $apiCsproj | Out-Null
        Write-Done "API  $($kv.Key)"
    }
}

# ─── 3. dotnet user-secrets (UI) ──────────────────────────────────────────────
Write-Step 'dotnet user-secrets — UI project'

if ($PSCmdlet.ShouldProcess("UI user-secrets: ApiSettings:UI:https:CertPassword")) {
    dotnet user-secrets set 'ApiSettings:UI:https:CertPassword' $certPassword --project $uiCsproj | Out-Null
    Write-Done "UI   ApiSettings:UI:https:CertPassword"
}

# ─── 4. HTTPS dev certificate ─────────────────────────────────────────────────
Write-Step 'HTTPS development certificate'

$certOutput = dotnet dev-certs https --check --quiet 2>&1
if ($LASTEXITCODE -eq 0 -and -not $Force) {
    Write-Skip 'dev cert already trusted'
}
else {
    # Export to PFX for Docker HTTPS profiles, then trust the system cert
    if ($PSCmdlet.ShouldProcess('HTTPS dev cert — export and trust')) {
        dotnet dev-certs https -ep $certFile -p $certPassword --overwrite | Out-Null
        dotnet dev-certs https --trust
        Write-Done "Cert exported to Resources/Certificates/aspnetapp.pfx and trusted"
    }
}

# ─── Summary ──────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '  Local setup complete!' -ForegroundColor Green
Write-Host ''
Write-Host '  Visual Studio F5 (http/https profile — no docker-* profiles):'
Write-Host '    API  http://localhost:5010/swagger'
Write-Host '    UI   http://localhost:5012'
Write-Host ''
Write-Host '  Docker dev:'
Write-Host '    .\Resources\Docker\start-docker.ps1 -Environment dev -Profile http'
Write-Host ''
Write-Host '  To use real OpenPay sandbox credentials, edit Resources\Docker\.env.local'
Write-Host '  and re-run:  dotnet user-secrets set OpenPay:MerchantId <real-id> --project .\XYDataLabs.OrderProcessingSystem.API\...'
Write-Host ''
