#Requires -Version 7.0
<#
.SYNOPSIS
    Bootstrap local development environment. Run once after a fresh clone.

.DESCRIPTION
    Performs all first-time setup needed to develop and run this project locally:
      1. Creates Resources/Docker/.env.local from .env.local.example (Docker secrets)
      2. Sets dotnet user-secrets for VS F5 and dotnet run (API + UI projects)
      3. Trusts the HTTPS development certificate

    These are LOCAL SANDBOX credentials only — they are never used in dev/staging/prod
    Azure environments. Override the defaults with your preferred values via parameters.

    This script is idempotent: re-running it skips steps that are already complete.

.PARAMETER CertPassword
    Password for the local HTTPS development certificate and Docker TLS.
    Used for both the .pfx file and the LOCAL_CERT_PASSWORD Docker secret.
    Default: Admin100@ — local sandbox only.

.PARAMETER SqlPassword
    SQL Server password for the local Docker SQL Server container.
    Used for the LOCAL_SQL_PASSWORD Docker secret.
    Default: Admin100@ — local sandbox only.

.PARAMETER Force
    Re-create .env.local and overwrite dotnet user-secrets even if they already exist.

.EXAMPLE
    # Zero-touch setup with defaults (for sandbox / CI-like environment)
    .\scripts\setup-local.ps1

.EXAMPLE
    # Custom passwords
    .\scripts\setup-local.ps1 -CertPassword 'My$ecure1!' -SqlPassword 'My$ecure1!'

.EXAMPLE
    # Re-run and overwrite everything (e.g. after changing passwords)
    .\scripts\setup-local.ps1 -Force

.NOTES
    After running this script:
      - F5 in Visual Studio 2022 is ready immediately (no prompts).
      - Docker: .\Resources\Docker\start-docker.ps1 -Environment dev -Profile http
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $CertPassword = 'Admin100@',
    [string] $SqlPassword  = 'Admin100@',
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ─── Paths ───────────────────────────────────────────────────────────────────
$root       = Split-Path $PSScriptRoot -Parent
$envExample = Join-Path $root 'Resources\Docker\.env.local.example'
$envLocal   = Join-Path $root 'Resources\Docker\.env.local'
$certFile   = Join-Path $root 'Resources\Certificates\aspnetapp.pfx'
$apiCsproj  = Join-Path $root 'XYDataLabs.OrderProcessingSystem.API\XYDataLabs.OrderProcessingSystem.API.csproj'
$uiCsproj   = Join-Path $root 'XYDataLabs.OrderProcessingSystem.UI\XYDataLabs.OrderProcessingSystem.UI.csproj'

# ─── Helpers ──────────────────────────────────────────────────────────────────
function Write-Step([string] $msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Done([string] $msg) { Write-Host "    [ok]  $msg" -ForegroundColor Green }
function Write-Skip([string] $msg) { Write-Host "    [--]  $msg (already done — skip)" -ForegroundColor DarkGray }

# ─── 1. Docker .env.local ─────────────────────────────────────────────────────
Write-Step 'Docker secrets — Resources/Docker/.env.local'

if ((Test-Path $envLocal) -and -not $Force) {
    Write-Skip '.env.local already exists'
}
else {
    if (-not (Test-Path $envExample)) {
        Write-Error "Expected template not found: $envExample"
    }

    $content = @"
# Local Docker secrets — auto-generated by setup-local.ps1
# Gitignored. Re-run setup-local.ps1 -Force to regenerate.
LOCAL_SQL_PASSWORD=$SqlPassword
LOCAL_CERT_PASSWORD=$CertPassword
LOCAL_OPENPAY_MERCHANT_ID=local-sandbox-only
LOCAL_OPENPAY_PRIVATE_KEY=local-sandbox-only
LOCAL_OPENPAY_DEVICE_SESSION_ID=default-device-session
"@
    Set-Content -Path $envLocal -Value $content -Encoding UTF8
    Write-Done "Created .env.local"
}

# ─── 2. dotnet user-secrets (API) ─────────────────────────────────────────────
Write-Step 'dotnet user-secrets — API project'

$apiSecrets = [ordered]@{
    'ApiSettings:API:https:CertPassword' = $CertPassword
    'OpenPay:MerchantId'                 = 'local-sandbox-only'
    'OpenPay:PrivateKey'                 = 'local-sandbox-only'
    'OpenPay:DeviceSessionId'            = 'default-device-session'
}

foreach ($kv in $apiSecrets.GetEnumerator()) {
    if ($PSCmdlet.ShouldProcess("API user-secrets: $($kv.Key)")) {
        dotnet user-secrets set $kv.Key $kv.Value --project $apiCsproj | Out-Null
        Write-Done "API  $($kv.Key)"
    }
}

# ─── 3. dotnet user-secrets (UI) ──────────────────────────────────────────────
Write-Step 'dotnet user-secrets — UI project'

if ($PSCmdlet.ShouldProcess("UI user-secrets: ApiSettings:UI:https:CertPassword")) {
    dotnet user-secrets set 'ApiSettings:UI:https:CertPassword' $CertPassword --project $uiCsproj | Out-Null
    Write-Done "UI   ApiSettings:UI:https:CertPassword"
}

# ─── 4. HTTPS dev certificate ─────────────────────────────────────────────────
Write-Step 'HTTPS development certificate'

$certOutput = dotnet dev-certs https --check --quiet 2>&1
if ($LASTEXITCODE -eq 0 -and -not $Force) {
    Write-Skip 'dev cert already trusted'
}
else {
    # Export to PFX for Docker HTTPS profiles, then trust the system cert
    if ($PSCmdlet.ShouldProcess('HTTPS dev cert — export and trust')) {
        dotnet dev-certs https -ep $certFile -p $CertPassword --overwrite | Out-Null
        dotnet dev-certs https --trust
        Write-Done "Cert exported to Resources/Certificates/aspnetapp.pfx and trusted"
    }
}

# ─── Summary ──────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '  Local setup complete!' -ForegroundColor Green
Write-Host ''
Write-Host '  Visual Studio F5 (http/https profile — no docker-* profiles):'
Write-Host '    API  http://localhost:5010/swagger'
Write-Host '    UI   http://localhost:5012'
Write-Host ''
Write-Host '  Docker dev:'
Write-Host '    .\Resources\Docker\start-docker.ps1 -Environment dev -Profile http'
Write-Host ''
Write-Host '  To use real OpenPay sandbox credentials, edit Resources\Docker\.env.local'
Write-Host '  and re-run:  dotnet user-secrets set OpenPay:MerchantId <real-id> --project .\XYDataLabs.OrderProcessingSystem.API\...'
Write-Host ''
