#Requires -Version 7.0
<#
.SYNOPSIS
    Bootstrap local development environment. Run once after a fresh clone.

.DESCRIPTION
    Performs all first-time setup needed to develop and run this project locally:
      1. Creates Resources/Docker/.env.local — prompts for passwords on first run,
         reads them from the existing file on subsequent runs.
    2. Sets dotnet user-secrets for the API project
    3. Trusts the HTTPS development certificate used by both API and frontend

    .env.local is the single source of truth for local passwords. All steps derive
    passwords from it — no hardcoded defaults, no parameters to pass.

    This script is idempotent: re-running it reads from the existing .env.local and
    re-applies API user-secrets and cert without prompting again.
    Use -Force to re-prompt for passwords and overwrite everything.

.PARAMETER Force
    Re-prompt for passwords, recreate .env.local, and overwrite API user-secrets
    and the dev certificate even if they already exist.

.EXAMPLE
    # First-time setup — prompts for SQL and cert passwords
    .\scripts\setup-local.ps1

.EXAMPLE
    # Re-run and overwrite everything (e.g. after a password change)
    .\scripts\setup-local.ps1 -Force

.NOTES
    After running this script:
      - F5 in Visual Studio 2022 is ready immediately (no prompts).
      - Docker: .\Resources\Docker\start-docker.ps1 -Environment dev -Profile http
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ─── Paths ───────────────────────────────────────────────────────────────────
$root       = Split-Path $PSScriptRoot -Parent
$envExample = Join-Path $root 'Resources\Docker\.env.local.example'
$envLocal   = Join-Path $root 'Resources\Docker\.env.local'
$certFile   = Join-Path $root 'Resources\Certificates\aspnetapp.pfx'
$apiCsproj  = Join-Path $root 'XYDataLabs.OrderProcessingSystem.API\XYDataLabs.OrderProcessingSystem.API.csproj'

# ─── Helpers ──────────────────────────────────────────────────────────────────
function Write-Step([string] $msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Done([string] $msg) { Write-Host "    [ok]  $msg" -ForegroundColor Green }
function Write-Skip([string] $msg) { Write-Host "    [--]  $msg (already done — skip)" -ForegroundColor DarkGray }

function Read-Password([string] $prompt) {
    $ss = Read-Host -Prompt $prompt -AsSecureString
    [System.Net.NetworkCredential]::new('', $ss).Password
}

function Read-EnvLocal([string] $path) {
    $vars = @{}
    Get-Content $path | Where-Object { $_ -match '^[A-Z]' } | ForEach-Object {
        $parts = $_ -split '=', 2
        if ($parts.Count -eq 2) { $vars[$parts[0].Trim()] = $parts[1].Trim() }
    }
    $vars
}

function Test-LooksLikeOpenPayPrivateKey([string] $value) {
    return -not [string]::IsNullOrWhiteSpace($value) -and $value -match '^sk_'
}

function Test-LooksLikeOpenPayMerchantId([string] $value) {
    return -not [string]::IsNullOrWhiteSpace($value) -and $value -notmatch '^sk_' -and $value -match '^[a-z0-9]{10,}$'
}

function Normalize-OpenPayCredentials {
    param(
        [string] $MerchantId,
        [string] $PrivateKey,
        [string] $SourceLabel
    )

    $normalizedMerchant = $MerchantId
    $normalizedPrivateKey = $PrivateKey
    $swapped = (Test-LooksLikeOpenPayPrivateKey $normalizedMerchant) -and (Test-LooksLikeOpenPayMerchantId $normalizedPrivateKey)

    if ($swapped) {
        Write-Host "    [!!] Detected swapped OpenPay Merchant ID and Private Key from $SourceLabel - normalizing values." -ForegroundColor Yellow
        $originalMerchant = $normalizedMerchant
        $normalizedMerchant = $normalizedPrivateKey
        $normalizedPrivateKey = $originalMerchant
    }

    [PSCustomObject] @{
        MerchantId = $normalizedMerchant
        PrivateKey = $normalizedPrivateKey
        WasSwapped = $swapped
    }
}

function New-EnvLocalContent {
    param(
        [Parameter(Mandatory = $true)] [string] $SqlPassword,
        [Parameter(Mandatory = $true)] [string] $CertPassword,
        [Parameter(Mandatory = $true)] [string] $KeycloakTenantAdminPassword,
        [Parameter(Mandatory = $true)] [string] $OpenPayMerchant,
        [Parameter(Mandatory = $true)] [string] $OpenPayPublicKey,
        [Parameter(Mandatory = $true)] [string] $OpenPayPrivateKey,
        [Parameter(Mandatory = $true)] [string] $OpenPayDeviceSessionId,
        [Parameter(Mandatory = $true)] [string] $RazorpayMerchantId,
        [Parameter(Mandatory = $true)] [string] $RazorpayPrivateKey,
        [string] $RazorpayWebhookSecret = 'local-sandbox-only',
        [string] $OpenPayWebhookSecret = 'local-sandbox-only',
        [string] $SqlServerImage = ''
    )

    $lines = @"
# Local Docker secrets - auto-generated by setup-local.ps1
# Gitignored. Re-run setup-local.ps1 -Force to change passwords.
LOCAL_SQL_PASSWORD=$SqlPassword
LOCAL_CERT_PASSWORD=$CertPassword
KEYCLOAK_TENANT_ADMIN_PASSWORD=$KeycloakTenantAdminPassword
LOCAL_OPENPAY_MERCHANT_ID=$OpenPayMerchant
LOCAL_OPENPAY_PUBLIC_KEY=$OpenPayPublicKey
LOCAL_OPENPAY_PRIVATE_KEY=$OpenPayPrivateKey
LOCAL_OPENPAY_DEVICE_SESSION_ID=$OpenPayDeviceSessionId
LOCAL_OPENPAY_WEBHOOK_SECRET=$OpenPayWebhookSecret
LOCAL_RAZORPAY_MERCHANT_ID=$RazorpayMerchantId
LOCAL_RAZORPAY_PRIVATE_KEY=$RazorpayPrivateKey
LOCAL_RAZORPAY_WEBHOOK_SECRET=$RazorpayWebhookSecret
"@

    if (-not [string]::IsNullOrWhiteSpace($SqlServerImage)) {
        $lines = $lines.TrimEnd("`r", "`n") + "`r`nORDERPROCESSING_SQLSERVER_IMAGE=$SqlServerImage`r`n"
    }

    return $lines
}

function Write-EnvLocal {
    param(
        [Parameter(Mandatory = $true)] [string] $Path,
        [Parameter(Mandatory = $true)] [string] $SqlPassword,
        [Parameter(Mandatory = $true)] [string] $CertPassword,
        [Parameter(Mandatory = $true)] [string] $KeycloakTenantAdminPassword,
        [Parameter(Mandatory = $true)] [string] $OpenPayMerchant,
        [Parameter(Mandatory = $true)] [string] $OpenPayPublicKey,
        [Parameter(Mandatory = $true)] [string] $OpenPayPrivateKey,
        [Parameter(Mandatory = $true)] [string] $OpenPayDeviceSessionId,
        [Parameter(Mandatory = $true)] [string] $RazorpayMerchantId,
        [Parameter(Mandatory = $true)] [string] $RazorpayPrivateKey,
        [string] $RazorpayWebhookSecret = 'local-sandbox-only',
        [string] $OpenPayWebhookSecret = 'local-sandbox-only',
        [string] $SqlServerImage = ''
    )

    $content = New-EnvLocalContent `
        -SqlPassword $SqlPassword `
        -CertPassword $CertPassword `
        -KeycloakTenantAdminPassword $KeycloakTenantAdminPassword `
        -OpenPayMerchant $OpenPayMerchant `
        -OpenPayPublicKey $OpenPayPublicKey `
        -OpenPayPrivateKey $OpenPayPrivateKey `
        -OpenPayDeviceSessionId $OpenPayDeviceSessionId `
        -RazorpayMerchantId $RazorpayMerchantId `
        -RazorpayPrivateKey $RazorpayPrivateKey `
        -RazorpayWebhookSecret $RazorpayWebhookSecret `
        -OpenPayWebhookSecret $OpenPayWebhookSecret `
        -SqlServerImage $SqlServerImage

    Set-Content -Path $Path -Value $content -Encoding UTF8
}

# ─── 1. Docker .env.local ─────────────────────────────────────────────────────
Write-Step 'Docker secrets — Resources/Docker/.env.local'

if ((Test-Path $envLocal) -and -not $Force) {
    Write-Skip '.env.local already exists — reading passwords from it'
    $envVars         = Read-EnvLocal $envLocal
    $certPassword    = $envVars['LOCAL_CERT_PASSWORD']
    $keycloakTenantAdminPassword = $envVars['KEYCLOAK_TENANT_ADMIN_PASSWORD']
    $sqlPassword     = $envVars['LOCAL_SQL_PASSWORD']
    $openpayMerchant = $envVars['LOCAL_OPENPAY_MERCHANT_ID']
    $openpayPublicKey = $envVars['LOCAL_OPENPAY_PUBLIC_KEY']
    $openpayKey      = $envVars['LOCAL_OPENPAY_PRIVATE_KEY']
    $openpaySession  = $envVars['LOCAL_OPENPAY_DEVICE_SESSION_ID']
    $razorpayMerchant = $envVars['LOCAL_RAZORPAY_MERCHANT_ID']
    $razorpayPrivateKey = $envVars['LOCAL_RAZORPAY_PRIVATE_KEY']
    $razorpayWebhookSecret = $envVars['LOCAL_RAZORPAY_WEBHOOK_SECRET']
    $openpayWebhookSecret  = $envVars['LOCAL_OPENPAY_WEBHOOK_SECRET']
    $sqlServerImage  = $envVars['ORDERPROCESSING_SQLSERVER_IMAGE']

    $normalizedEnvCredentials = Normalize-OpenPayCredentials `
        -MerchantId $openpayMerchant `
        -PrivateKey $openpayKey `
        -SourceLabel '.env.local'

    $openpayMerchant = $normalizedEnvCredentials.MerchantId
    $openpayKey = $normalizedEnvCredentials.PrivateKey

    $envLocalWasIncomplete = $false

    if ([string]::IsNullOrWhiteSpace($sqlPassword)) {
        Write-Host '    [!!] LOCAL_SQL_PASSWORD is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $sqlPassword = Read-Password '  Choose SQL Server password (LOCAL_SQL_PASSWORD) '
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($certPassword)) {
        Write-Host '    [!!] LOCAL_CERT_PASSWORD is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $certPassword = Read-Password '  Choose HTTPS cert password (LOCAL_CERT_PASSWORD) '
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($keycloakTenantAdminPassword)) {
        Write-Host '    [!!] KEYCLOAK_TENANT_ADMIN_PASSWORD is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $keycloakTenantAdminPassword = Read-Password '  Choose Keycloak tenant admin password (KEYCLOAK_TENANT_ADMIN_PASSWORD) '
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($openpayMerchant)) {
        Write-Host '    [!!] LOCAL_OPENPAY_MERCHANT_ID is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $openpayMerchant = (Read-Host '  OpenPay Merchant ID (LOCAL_OPENPAY_MERCHANT_ID) ').Trim()
        if ([string]::IsNullOrWhiteSpace($openpayMerchant)) { $openpayMerchant = 'local-sandbox-only' }
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($openpayKey)) {
        Write-Host '    [!!] LOCAL_OPENPAY_PRIVATE_KEY is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $openpayKey = (Read-Host '  OpenPay Private Key (LOCAL_OPENPAY_PRIVATE_KEY) ').Trim()
        if ([string]::IsNullOrWhiteSpace($openpayKey)) { $openpayKey = 'local-sandbox-only' }
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($openpayPublicKey)) {
        Write-Host '    [!!] LOCAL_OPENPAY_PUBLIC_KEY is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $openpayPublicKey = (Read-Host '  OpenPay Public Key (LOCAL_OPENPAY_PUBLIC_KEY) ').Trim()
        if ([string]::IsNullOrWhiteSpace($openpayPublicKey)) { $openpayPublicKey = 'local-sandbox-only' }
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($razorpayMerchant)) {
        Write-Host '    [!!] LOCAL_RAZORPAY_MERCHANT_ID is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $razorpayMerchant = (Read-Host '  Razorpay Merchant ID (LOCAL_RAZORPAY_MERCHANT_ID) ').Trim()
        if ([string]::IsNullOrWhiteSpace($razorpayMerchant)) { $razorpayMerchant = 'local-sandbox-only' }
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($razorpayPrivateKey)) {
        Write-Host '    [!!] LOCAL_RAZORPAY_PRIVATE_KEY is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $razorpayPrivateKey = (Read-Host '  Razorpay Private Key (LOCAL_RAZORPAY_PRIVATE_KEY) ').Trim()
        if ([string]::IsNullOrWhiteSpace($razorpayPrivateKey)) { $razorpayPrivateKey = 'local-sandbox-only' }
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($razorpayWebhookSecret)) {
        Write-Host '    [!!] LOCAL_RAZORPAY_WEBHOOK_SECRET is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $razorpayWebhookSecret = (Read-Host '  Razorpay Webhook Secret (LOCAL_RAZORPAY_WEBHOOK_SECRET) ').Trim()
        if ([string]::IsNullOrWhiteSpace($razorpayWebhookSecret)) { $razorpayWebhookSecret = 'local-sandbox-only' }
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($openpayWebhookSecret)) {
        Write-Host '    [!!] LOCAL_OPENPAY_WEBHOOK_SECRET is missing from .env.local - prompting to repair it.' -ForegroundColor Yellow
        $openpayWebhookSecret = (Read-Host '  OpenPay Webhook Secret (LOCAL_OPENPAY_WEBHOOK_SECRET) ').Trim()
        if ([string]::IsNullOrWhiteSpace($openpayWebhookSecret)) { $openpayWebhookSecret = 'local-sandbox-only' }
        $envLocalWasIncomplete = $true
    }

    if ([string]::IsNullOrWhiteSpace($openpaySession)) {
        Write-Host '    [!!] LOCAL_OPENPAY_DEVICE_SESSION_ID is missing from .env.local - defaulting it.' -ForegroundColor Yellow
        $openpaySession = 'default-device-session'
        $envLocalWasIncomplete = $true
    }

    if ($normalizedEnvCredentials.WasSwapped -or $envLocalWasIncomplete) {
        Write-EnvLocal `
            -Path $envLocal `
            -SqlPassword $sqlPassword `
            -CertPassword $certPassword `
            -KeycloakTenantAdminPassword $keycloakTenantAdminPassword `
            -OpenPayMerchant $openpayMerchant `
            -OpenPayPublicKey $openpayPublicKey `
            -OpenPayPrivateKey $openpayKey `
            -OpenPayDeviceSessionId $openpaySession `
            -RazorpayMerchantId $razorpayMerchant `
            -RazorpayPrivateKey $razorpayPrivateKey `
            -RazorpayWebhookSecret $razorpayWebhookSecret `
            -OpenPayWebhookSecret $openpayWebhookSecret `
            -SqlServerImage $sqlServerImage

        Write-Done 'Repaired .env.local'
    }
}
else {
    if (-not (Test-Path $envExample)) {
        Write-Error "Expected template not found: $envExample"
    }

    Write-Host '  Choose passwords for your local sandbox — you are setting these for the first time.' -ForegroundColor Yellow
    Write-Host '  They will be saved to .env.local and used for every subsequent run.' -ForegroundColor Yellow
    Write-Host '  SQL Server requires: 8+ chars, uppercase, lowercase, digit, special char (e.g. MyLocal1!)' -ForegroundColor DarkGray
    Write-Host ''
    $sqlPassword  = Read-Password '  Choose SQL Server password (LOCAL_SQL_PASSWORD) '
    $certPassword = Read-Password '  Choose HTTPS cert password (LOCAL_CERT_PASSWORD) '
    $keycloakTenantAdminPassword = Read-Password '  Choose Keycloak tenant admin password (KEYCLOAK_TENANT_ADMIN_PASSWORD) '

    Write-Host ''
    Write-Host '  OpenPay sandbox credentials — fetching from Key Vault kv-orderprocessing-dev...' -ForegroundColor Yellow
    $openpayMerchant = $null
    $openpayPublicKey = $null
    $openpayKey      = $null
    $openpaySession  = 'default-device-session'
    $razorpayMerchant = $null
    $razorpayPrivateKey = $null
    $razorpayWebhookSecret = $null
    $openpayWebhookSecret  = $null
    $sqlServerImage  = if (Test-Path $envLocal) { (Read-EnvLocal $envLocal)['ORDERPROCESSING_SQLSERVER_IMAGE'] } else { '' }

    $azAvailable = Get-Command az -ErrorAction SilentlyContinue
    if ($azAvailable) {
        try {
            $kvMerchant = az keyvault secret show --vault-name kv-orderprocessing-dev --name 'OpenPay--MerchantId' --query value -o tsv 2>$null
            $kvPublicKey = az keyvault secret show --vault-name kv-orderprocessing-dev --name 'OpenPay--PublicKey' --query value -o tsv 2>$null
            $kvKey      = az keyvault secret show --vault-name kv-orderprocessing-dev --name 'OpenPay--PrivateKey'  --query value -o tsv 2>$null
            $kvRazorpayMerchant = az keyvault secret show --vault-name kv-orderprocessing-dev --name 'Razorpay--MerchantId' --query value -o tsv 2>$null
            $kvRazorpayKey = az keyvault secret show --vault-name kv-orderprocessing-dev --name 'Razorpay--PrivateKey' --query value -o tsv 2>$null
            $kvRazorpayWebhook = az keyvault secret show --vault-name kv-orderprocessing-dev --name 'Webhooks--Razorpay--Secret' --query value -o tsv 2>$null
            $kvOpenpayWebhook  = az keyvault secret show --vault-name kv-orderprocessing-dev --name 'Webhooks--OpenPay--Secret'  --query value -o tsv 2>$null
            if ($kvMerchant -and $kvKey -and
                $kvMerchant -notmatch '^set-openpay' -and $kvKey -notmatch '^set-openpay') {
                $normalizedKvCredentials = Normalize-OpenPayCredentials `
                    -MerchantId $kvMerchant.Trim() `
                    -PrivateKey $kvKey.Trim() `
                    -SourceLabel 'Key Vault kv-orderprocessing-dev'

                $openpayMerchant = $normalizedKvCredentials.MerchantId
                $openpayKey      = $normalizedKvCredentials.PrivateKey
                if ($kvPublicKey -and $kvPublicKey -notmatch '^set-openpay' -and $kvPublicKey -ne '__OPENPAY_PUBLIC_KEY__') {
                    $openpayPublicKey = $kvPublicKey.Trim()
                }
                if ($kvRazorpayMerchant -and $kvRazorpayMerchant -notmatch '^set-razorpay' -and $kvRazorpayMerchant -ne '__RAZORPAY_MERCHANT_ID__') {
                    $razorpayMerchant = $kvRazorpayMerchant.Trim()
                }
                if ($kvRazorpayKey -and $kvRazorpayKey -notmatch '^set-razorpay' -and $kvRazorpayKey -ne '__RAZORPAY_PRIVATE_KEY__') {
                    $razorpayPrivateKey = $kvRazorpayKey.Trim()
                }
                if ($kvRazorpayWebhook -and $kvRazorpayWebhook -notmatch '^local-sandbox-only' -and $kvRazorpayWebhook -ne '__RAZORPAY_WEBHOOK_SECRET__') {
                    $razorpayWebhookSecret = $kvRazorpayWebhook.Trim()
                }
                if ($kvOpenpayWebhook -and $kvOpenpayWebhook -notmatch '^local-sandbox-only' -and $kvOpenpayWebhook -ne '__OPENPAY_WEBHOOK_SECRET__') {
                    $openpayWebhookSecret = $kvOpenpayWebhook.Trim()
                }
                if ($normalizedKvCredentials.WasSwapped) {
                    Write-Host '    [!!] kv-orderprocessing-dev still stores OpenPay--MerchantId and OpenPay--PrivateKey under the wrong names. Local setup will continue with normalized values, but the Key Vault source should be corrected separately.' -ForegroundColor Yellow
                }
                Write-Done 'OpenPay credentials fetched from kv-orderprocessing-dev'
            } else {
                Write-Host '  [--]  Key Vault returned placeholder values — falling back to prompt.' -ForegroundColor DarkGray
            }
        } catch {
            Write-Host "  [--]  Could not read from Key Vault: $($_.Exception.Message)" -ForegroundColor DarkGray
        }
    } else {
        Write-Host '  [--]  az CLI not found — skipping Key Vault fetch.' -ForegroundColor DarkGray
    }

    if (-not $openpayMerchant) {
        Write-Host ''
        Write-Host '  ┌─────────────────────────────────────────────────────────────────┐' -ForegroundColor Cyan
        Write-Host '  │  OpenPay sandbox credentials — manual step required             │' -ForegroundColor Cyan
        Write-Host '  ├─────────────────────────────────────────────────────────────────┤' -ForegroundColor Cyan
        Write-Host '  │  1. Open https://sandbox-dashboard.openpay.mx                   │' -ForegroundColor Cyan
        Write-Host '  │  2. Log in to your sandbox account                              │' -ForegroundColor Cyan
        Write-Host '  │  3. On the home/dashboard page you will see:                    │' -ForegroundColor Cyan
        Write-Host '  │       Merchant ID  — a short alphanumeric string (e.g. m...)    │' -ForegroundColor Cyan
        Write-Host '  │       Public key   — starts with pk_...                         │' -ForegroundColor Cyan
        Write-Host '  │       Private key  — starts with sk_...                         │' -ForegroundColor Cyan
        Write-Host '  │  4. Paste the OpenPay values below, then Razorpay if used.      │' -ForegroundColor Cyan
        Write-Host '  │                                                                 │' -ForegroundColor Cyan
        Write-Host '  │  These are stored in .env.local (gitignored) and user-secrets.  │' -ForegroundColor Cyan
        Write-Host '  │  You will NOT be asked again on subsequent runs.                │' -ForegroundColor Cyan
        Write-Host '  │                                                                 │' -ForegroundColor Cyan
        Write-Host '  │  To store them in Azure Key Vault so future team members and    │' -ForegroundColor Cyan
        Write-Host '  │  machines get them automatically, run once after pasting:       │' -ForegroundColor Cyan
        Write-Host '  │    .\Resources\Azure-Deployment\populate-keyvault-secrets.ps1   │' -ForegroundColor Cyan
        Write-Host '  │        -Environment dev                                         │' -ForegroundColor Cyan
        Write-Host '  │        -OpenPayMerchantId <id> -OpenPayPublicKey <key>          │' -ForegroundColor Cyan
        Write-Host '  │        -OpenPayPrivateKey <key>                                  │' -ForegroundColor Cyan
        Write-Host '  │                                                                 │' -ForegroundColor Cyan
        Write-Host '  │  Leave blank to skip — payment calls will fail (error 1002)     │' -ForegroundColor Cyan
        Write-Host '  │  until credentials are set.                                     │' -ForegroundColor Cyan
        Write-Host '  └─────────────────────────────────────────────────────────────────┘' -ForegroundColor Cyan
        Write-Host ''
        $openpayMerchant = (Read-Host '  OpenPay Merchant ID (LOCAL_OPENPAY_MERCHANT_ID) ').Trim()
        $openpayPublicKey = (Read-Host '  OpenPay Public Key (LOCAL_OPENPAY_PUBLIC_KEY)   ').Trim()
        $openpayKey      = (Read-Host '  OpenPay Private Key (LOCAL_OPENPAY_PRIVATE_KEY)  ').Trim()
        if ([string]::IsNullOrWhiteSpace($openpayMerchant)) { $openpayMerchant = 'local-sandbox-only' }
        if ([string]::IsNullOrWhiteSpace($openpayPublicKey)) { $openpayPublicKey = 'local-sandbox-only' }
        if ([string]::IsNullOrWhiteSpace($openpayKey))      { $openpayKey      = 'local-sandbox-only' }
    }

    if (-not $razorpayMerchant) {
        $razorpayMerchant = (Read-Host '  Razorpay Merchant ID (LOCAL_RAZORPAY_MERCHANT_ID) ').Trim()
        if ([string]::IsNullOrWhiteSpace($razorpayMerchant)) { $razorpayMerchant = 'local-sandbox-only' }
    }

    if (-not $razorpayPrivateKey) {
        $razorpayPrivateKey = (Read-Host '  Razorpay Private Key (LOCAL_RAZORPAY_PRIVATE_KEY) ').Trim()
        if ([string]::IsNullOrWhiteSpace($razorpayPrivateKey)) { $razorpayPrivateKey = 'local-sandbox-only' }
    }

    if (-not $razorpayWebhookSecret) {
        $razorpayWebhookSecret = (Read-Host '  Razorpay Webhook Secret (LOCAL_RAZORPAY_WEBHOOK_SECRET) [leave blank to skip] ').Trim()
        if ([string]::IsNullOrWhiteSpace($razorpayWebhookSecret)) { $razorpayWebhookSecret = 'local-sandbox-only' }
    }

    if (-not $openpayWebhookSecret) {
        $openpayWebhookSecret = (Read-Host '  OpenPay Webhook Secret (LOCAL_OPENPAY_WEBHOOK_SECRET) [leave blank to skip]   ').Trim()
        if ([string]::IsNullOrWhiteSpace($openpayWebhookSecret)) { $openpayWebhookSecret = 'local-sandbox-only' }
    }

    if (-not $openpayPublicKey) {
        $openpayPublicKey = (Read-Host '  OpenPay Public Key (LOCAL_OPENPAY_PUBLIC_KEY) ').Trim()
        if ([string]::IsNullOrWhiteSpace($openpayPublicKey)) { $openpayPublicKey = 'local-sandbox-only' }
    }

    Write-EnvLocal `
        -Path $envLocal `
        -SqlPassword $sqlPassword `
        -CertPassword $certPassword `
        -KeycloakTenantAdminPassword $keycloakTenantAdminPassword `
        -OpenPayMerchant $openpayMerchant `
        -OpenPayPublicKey $openpayPublicKey `
        -OpenPayPrivateKey $openpayKey `
        -OpenPayDeviceSessionId $openpaySession `
        -RazorpayMerchantId $razorpayMerchant `
        -RazorpayPrivateKey $razorpayPrivateKey `
        -RazorpayWebhookSecret $razorpayWebhookSecret `
        -OpenPayWebhookSecret $openpayWebhookSecret `
        -SqlServerImage $sqlServerImage

    Write-Done 'Created .env.local'
}

# ─── 2. dotnet user-secrets (API) ─────────────────────────────────────────────
Write-Step 'dotnet user-secrets — API project'

$apiSecrets = [ordered]@{
    'ApiSettings:API:https:CertPassword'          = $certPassword
    'OpenPay:MerchantId'                          = $openpayMerchant
    'OpenPay:PublicKey'                           = $openpayPublicKey
    'OpenPay:PrivateKey'                          = $openpayKey
    'OpenPay:DeviceSessionId'                     = $openpaySession
    'Razorpay:MerchantId'                         = $razorpayMerchant
    'Razorpay:PrivateKey'                         = $razorpayPrivateKey
    'Webhooks:Razorpay:Secret'                    = $razorpayWebhookSecret
    'Webhooks:OpenPay:Secret'                     = $openpayWebhookSecret
    'PaymentProviders:TenantA:OpenPay:PrivateKey' = $openpayKey
    'PaymentProviders:TenantB:OpenPay:PrivateKey' = $openpayKey
    'PaymentProviders:TenantC:OpenPay:PrivateKey' = $openpayKey
    'PaymentProviders:TenantA:Razorpay:PrivateKey' = $razorpayPrivateKey
    'PaymentProviders:TenantB:Razorpay:PrivateKey' = $razorpayPrivateKey
    'PaymentProviders:TenantC:Razorpay:PrivateKey' = $razorpayPrivateKey
}

foreach ($kv in $apiSecrets.GetEnumerator()) {
    if ($PSCmdlet.ShouldProcess("API user-secrets: $($kv.Key)")) {
        dotnet user-secrets set $kv.Key $kv.Value --project $apiCsproj | Out-Null
        Write-Done "API  $($kv.Key)"
    }
}

# ─── 3. HTTPS dev certificate ─────────────────────────────────────────────────
Write-Step 'HTTPS development certificate'

dotnet dev-certs https --check --quiet 2>$null | Out-Null
$certAlreadyTrusted = ($LASTEXITCODE -eq 0)

# Always (re-)export the PFX with the current LOCAL_CERT_PASSWORD so the file stays
# in sync with .env.local — even if the system cert is already trusted.
# Skipping this step when already trusted was the root cause of cert password mismatch
# on stg/https profiles: the file had an old password but .env.local had a new one.
if ($PSCmdlet.ShouldProcess('HTTPS dev cert — export to PFX')) {
    dotnet dev-certs https --export-path $certFile --password $certPassword | Out-Null
    Write-Done "Cert exported to Resources/Certificates/aspnetapp.pfx (password synced with .env.local)"
}

if ($certAlreadyTrusted -and -not $Force) {
    Write-Skip 'dev cert already trusted'
}
else {
    if ($PSCmdlet.ShouldProcess('HTTPS dev cert — trust')) {
        dotnet dev-certs https --trust
        Write-Done "Dev cert trusted"
    }
}

# ─── Summary ──────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '  Local setup complete!' -ForegroundColor Green
Write-Host ''
Write-Host '  Visual Studio F5 (http/https profile — no docker-* profiles):'
Write-Host '    API  http://localhost:5010/swagger'
Write-Host '    Web  http://localhost:5173   |   https://localhost:5174'
Write-Host ''
Write-Host '  Docker dev:'
Write-Host '    .\Resources\Docker\start-docker.ps1 -Environment dev -Profile http'
Write-Host ''
  if ($openpayMerchant -eq 'local-sandbox-only') {
      Write-Host '  OpenPay sandbox credentials were skipped. To add them later, run:' -ForegroundColor Yellow
      Write-Host '    .\scripts\setup-local.ps1 -Force' -ForegroundColor DarkGray
  }
Write-Host ''
