<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.Eventing.Abstractions\XYDataLabs.OrderProcessingSystem.Eventing.Abstractions.csproj" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.Orders.Domain\XYDataLabs.OrderProcessingSystem.Orders.Domain.csproj" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.Application\XYDataLabs.OrderProcessingSystem.Application.csproj" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.Inventory.API\XYDataLabs.OrderProcessingSystem.Inventory.API.csproj" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.Inventory.Features\XYDataLabs.OrderProcessingSystem.Inventory.Features.csproj" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.Orders.Contracts\XYDataLabs.OrderProcessingSystem.Orders.Contracts.csproj" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.Payments.Contracts\XYDataLabs.OrderProcessingSystem.Payments.Contracts.csproj" />
    <ProjectReference Include="..\XYDataLabs.OrderProcessingSystem.SharedKernel\XYDataLabs.OrderProcessingSystem.SharedKernel.csproj" />
  </ItemGroup>

</Project>

